### ISSUE TITLE
Struggling to Solve MPE Environments that involve communication using torchrl

### ISSUE THREAD

**Issue by SashaBoguraev** [proroklab/VectorizedMultiAgentSimulator#62] opened 2023-10-25 19:54 UTC
I first want to say thank you so much for developing this vectorized simulator, and further including the MPE environments. This saves me a lot of work that would have gone into vectorizing my MPE adaptations! This is not a bug in this codebase, more of a question.

I was just playing around with the tutorial that uses torchrl PPO to solve the navigation environment, and was attempting to follow it to solve simple_reference, but was running into an issue where the episode_reward_mean has values with extremely high magnitudes (from around -60 all the way to -180 at times). I was investigating the values calculated for rewards, and these all seemed to be as expected, but the objective and critic loss seem to be much larger than in other torchrl examples given. 

I was able to solve the non-vectorized version of the MPE using StableBaselines3 (SB3), but given VMAS doesn't natively support SB3 I wanted to try out torchrl. I was wondering if there is a pointer towards issues that may exist in merely using the given tutorial to solve any of the MPEs that involve communication? (I didn't think there was too much that was task specific -- I changed parameter sharing and critic centralization as necessary) And if so what may be the best way to go about this?

**Comment by matteobettini** [comment] 2023-10-25 20:40
Hey, thanks a lot for this, it is really appreaciated!

There are several things that we could investigate to see if there actually is a problem and where it is, here are some thoughts:
- the MAPPO/IPPO tutorial has very poor hyperparametrs and it is not supposed to be used for actual training of a real task. Have you tried seeing if you get the same problem in the [mappo_ippo script](https://github.com/pytorch/rl/blob/main/examples/multiagent/mappo_ippo.py)?
- we have recently released [BenchMARL](https://github.com/pytorch/rl/blob/main/examples/multiagent/mappo_ippo.py), a MARL traning library that uses TorchRL. You can actually try to train `simple_reference` in that library. For now there is only the non-vectorized version from pettingzoo, but you can easily add a new task with the vmas vectorized version (it is on our to do list). If the PettingZoo `simple_reference` in there has the problem you talked about, then it comes from TorchRL, otherwise it comes from VMAS.
- To see if the problem is in the VMAS implementation you can train vmas in RLlib and see if the issue still occurs.
- Put breakpoints in the vmas simple_reference file to check that all is doing what you expect it to do.

These steps should help identify the source of the issue, if any of these are able to help you pinpoint the problem let me know and I can fix it (either in TorchRL or VMAS, depending on the source).

I'll also try to do some investigation on my side

**Comment by matteobettini** [comment] 2023-10-25 21:34
I think I found something.
Some of the MPE scenarios (among which simple_reference) have a `self.collaborative` flag which indicates that rewards should be shared. 

In VMAS we did not have this flag.
I have added it in my local version and am testing if simple_reference will train.

I'll keep you posted on the results and then  push the fix

**Comment by SashaBoguraev** [comment] 2023-10-25 22:53
Hi matteo thanks for your response! Let me know how the change you found ends up working out. In the meantime I will work through the list of your suggestions tonight and update here if I find anything.

**Comment by SashaBoguraev** [comment] 2023-10-26 00:07
Hi Matteo not sure this is more relevant in this discussion or in an issue for BenchMARL, but when I try to run BenchMARL on Simple_Reference, I get the following output and error:

Command: `python3 benchmarl/run.py algorithm=mappo task=pettingzoo/simple_reference`

> Error executing job with overrides: ['algorithm=mappo', 'task=pettingzoo/simple_reference']
> Traceback (most recent call last):
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/benchmarl/run.py", line 25, in hydra_experiment
>     experiment.run()
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/benchmarl/experiment/experiment.py", line 516, in run
>     raise err
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/benchmarl/experiment/experiment.py", line 508, in run
>     self._collection_loop()
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/benchmarl/experiment/experiment.py", line 560, in _collection_loop
>     training_tds.append(self._optimizer_loop(group))
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/benchmarl/experiment/experiment.py", line 646, in _optimizer_loop
>     self.losses[group]
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/tensordict/tensordict.py", line 3623, in __getitem__
>     return self._get_tuple(idx_unravel, NO_DEFAULT)
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/tensordict/tensordict.py", line 4551, in _get_tuple
>     first = self._get_str(key[0], default)
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/tensordict/tensordict.py", line 4547, in _get_str
>     return self._default_get(first_key, default)
>   File "/Users/sashaboguraev/Desktop/Cornell/College Scholar/BenchMARL/lib/python3.10/site-packages/tensordict/tensordict.py", line 1455, in _default_get
>     raise KeyError(
> KeyError: 'key "finn" not found in TensorDict with keys [\'mlp\']'

**Comment by SashaBoguraev** [comment] 2023-10-26 00:44
I am currently training in RLlib and getting the same behavior, so this must be coming from the VMAS adaptation. I will parse the files and update here if I find anything other than the self.collaborative flag.

**Comment by matteobettini** [comment] 2023-10-26 07:03
Hey

I think i found the issue, it seems to be from the reset strategy (the uniform spawning of the agents )

**Comment by matteobettini** [comment] 2023-10-26 07:14
> Hi Matteo not sure this is more relevant in this discussion or in an issue for BenchMARL, but when I try to run BenchMARL on Simple_Reference, I get the following output and error:

this should be fixed, sorry

**Comment by matteobettini** [comment] 2023-10-26 07:31
The reason of the very negative values in the episode rewards is because we use episodes of 100 steps. This might be more than what you used in sb3 (PettingZoo defaults to 25 steps). 

That said, I trained simple_reference with ppo after the fixes of resetting and collaoration and I got these results
![W B Chart 26_10_2023, 08_28_47](https://github.com/proroklab/VectorizedMultiAgentSimulator/assets/55539777/7cd645f0-f94e-4304-a741-a4ac21b407b4)


![W B Chart 26_10_2023, 08_29_50](https://github.com/proroklab/VectorizedMultiAgentSimulator/assets/55539777/dc4941fd-d2dd-45e7-af1d-5e782e6e6e25)


The task is learning but MAPPO is not solving the task yet. I am trying MADDPG to see.

Does sb3 solve the task? if so could you share the hyperparams? and also are you using the pettingzoo verson of mpe or the original one?

**Comment by SashaBoguraev** [comment] 2023-10-26 15:32
Hi Matteo, this is great news! Thank you for the explanation of everything. I think that it makes sense for VMAS to conform to the traditional MPE rewards structure instead of the PettingZoo one. If one needs the other reward structure, it is not too difficult to change anyway. These steps sounds good, thank you so much for all your assistance here!

**Comment by matteobettini** [comment] 2023-10-27 11:04
Ok i ll tag you along the way

**Closed by matteobettini** 2023-10-27 11:04 UTC

**Comment by SashaBoguraev** [comment] 2023-10-30 15:10
Hi matteo, sorry to bother you again. When you trained using MADDPG, were you using the baseline hyperparameters in `maddpg_iddpg.yaml`? These don't seem to solve the problem for me, although i am currently trying to tune.

**Comment by matteobettini** [comment] 2023-10-30 15:38
Hey,


I used the fine_tuned vmas parameters from BenchMARL



<https://github.com/facebookresearch/BenchMARL/tree/3d62fc0903e70df9b4fc15da6138fffa7b337dfd/fine_tuned/vmas/conf>
[BenchMARL.png]
BenchMARL/fine_tuned/vmas/conf at 3d62fc0903e70df9b4fc15da6138fffa7b337dfd · facebookresearch/BenchMARL<https://github.com/facebookresearch/BenchMARL/tree/3d62fc0903e70df9b4fc15da6138fffa7b337dfd/fine_tuned/vmas/conf>
github.com<https://github.com/facebookresearch/BenchMARL/tree/3d62fc0903e70df9b4fc15da6138fffa7b337dfd/fine_tuned/vmas/conf>

Best

On 30 Oct 2023, at 16:11, SashaBoguraev ***@***.***> wrote:

﻿

Hi matteo, sorry to bother you again. When you trained using MADDPG, were you using the baseline hyperparameters in maddpg_iddpg.yaml? These don't seem to solve the problem for me, although i am currently trying to tune.

**Comment by SashaBoguraev** [comment] 2023-10-31 17:33
Thank you! My agents were able to learn the task. Thank you for all the help.
